name: Next.js Frontend CI/CD

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Verify Build Output
        run: |
          echo "Checking project files"
          ls -la
          echo "Checking Next.js build folder"
          ls -la .next || echo ".next folder not found"

      - name: Start Next.js Server
        run: |
          npm start &
          echo "Waiting for server..."
          sleep 15

      - name: Test Server
        run: |
          curl -v http://localhost:3000 || exit 1
